os: osx
language: c
branches:
  only: master
compiler:
- clang
cache:
  ccache: true
  directories:
  - config.cache
install:
- HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache freetype
  jpeg libpng libtiff libtool little-cms2 openjpeg webp xz libxml2 || true
- export PATH="/usr/local/opt/ccache/libexec:$PATH"
- export CCACHE_COMPRESS=""
- sysctl -n hw.ncpu
- sysctl -n hw.physicalcpu
env:
  global:
  - MAKEFLAGS="-j $(sysctl -n hw.ncpu)"
script: |
  set -e
  set -x
  export CFLAGS="-Wno-deprecated-declarations -Wdeclaration-after-statement -Wno-error=unused-variable"
  ls -la ./config.cache/
  ./configure --cache-file=./config.cache --enable-osx-universal-binary=no --disable-dependency-tracking --disable-silent-rules --enable-static --disable-shared --without-perl --disable-opencl --disable-openmp --with-freetype=yes --with-modules --with-webp=yes --with-openjp2 --without-gslib --without-fftw --without-pango --without-x --without-wmf --with-magick-plus-plus=no --with-rsvg=no --with-gvc=no --with-quantum-depth=16 --enable-delegate-build --prefix='/usr/local' --with-raw=yes
  ls -la ./config.cache/
  make
  mkdir out-build
  mkdir out-dmg
  make DEST_DIR=$PWD/out-build install
  pkgbuild --root ./out-build/ -i com.imagemagick --install-location / out-dmg/imagemagick.pkg
  hdiutil makehybrid -hfs -hfs-volume-name imagemagick -o ./imagemagick.dmg out-dmg
  hdiutil attach imagemagick.dmg
  ls -la /Volumes/imagemagick/
  sudo installer -package /Volumes/imagemagick/imagemagick.pkg -target /
  ls -la /usr/local/bin/magick || true
  hdiutil detach /Volumes/imagemagick
  magick logo: logo.gif
  identify logo.gif
deploy:
  provider: releases
  api_key:
    secure: aw/18h8HTHVyerfQRtaVXSfNhgARUpK4Nm5uaJK6l4oT1oEAcaO57pifovXMfYcnhNPuxMyrqnx7jOqvBoL48ovzfaOhdxFGFriTmTK/XCH7GfA3qkUo4NlZriScOHzJ31v5hsmLukkO/nWfTMjKFLtb+fMejjFhPF7zQCx7pUb/nuAf6i5+haZw9N/THIIoZpLQDgr+ZKT3UFM1N318Ndq3I/r6+KEz9tpMuMdz+4e0MZz2chgkgWebGzZM7mJFUCtPzy8Dr4kCFyUkhKr5v2bMQclVnOh48ZgzyKUXsSf4zg6b4+QnNkaYbBfpYKBXazRLEkhO1Tax1mgD6lW8dN+jHrnJD6es/VCmU7RcYK1whtcy24lqolOjiCGeqec+1p4Y1Fu//pIPDtLT01QzqbERa3WOOOnUakQjhbrJZpINmttw7F9PMeIeohXV7EqEaicUtHiDadhvSHynRcgW/mufnfclnBO4kiifA1jGUpjQrgLVtuaEM+PMqm7zAwTDfxlDp1pJUq3A5FSFmniBmnKn7EiMEehMqzev6BtQnyuFsUnJVg2pz/r0V0XQ8DoCGH2vWxxvzARme2R/GkZQbBjDefIEyAzg2O5RHZY5XJWeYMu4YQPwgyTFnDDTT/6fo5Cz9uzA5cPHytKRlOVM/16ziRIMdEHFZofv2OVOIi0=
  file: imagemagick.dmg
  on:
    repo: davehouse/ImageMagick
  skip_cleanup: 'true'
  edge: true
